-- Customer task system
-- Typed, RLS-protected follow-up tasks for each customer.

CREATE TYPE task_type AS ENUM ('call_back', 'refund', 'follow_up', 'order_issue', 'other');
CREATE TYPE task_status AS ENUM ('open', 'done');

CREATE TABLE customer_tasks (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_phone text        NOT NULL REFERENCES customers(phone) ON DELETE CASCADE,
  type           task_type   NOT NULL,
  body           text        NOT NULL CHECK (char_length(body) <= 500),
  status         task_status NOT NULL DEFAULT 'open',
  created_by     text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  completed_at   timestamptz,
  updated_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN customer_tasks.id             IS 'Primary key, UUID generated by default.';
COMMENT ON COLUMN customer_tasks.customer_phone IS 'E.164 phone of the customer this task belongs to. Cascades on customer deletion.';
COMMENT ON COLUMN customer_tasks.type           IS 'Category of the task: call_back, refund, follow_up, order_issue, or other.';
COMMENT ON COLUMN customer_tasks.body           IS 'Free-text description of the task. Maximum 500 characters.';
COMMENT ON COLUMN customer_tasks.status         IS 'open = actionable; done = completed.';
COMMENT ON COLUMN customer_tasks.created_by     IS 'Email of the admin user who created this task.';
COMMENT ON COLUMN customer_tasks.created_at     IS 'When the task was created.';
COMMENT ON COLUMN customer_tasks.completed_at   IS 'When the task was marked done. NULL if still open.';
COMMENT ON COLUMN customer_tasks.updated_at     IS 'Last write timestamp, maintained by trigger.';

ALTER TABLE customer_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated select customer_tasks"
  ON customer_tasks FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated insert customer_tasks"
  ON customer_tasks FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated update customer_tasks"
  ON customer_tasks FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE INDEX customer_tasks_customer_phone_idx ON customer_tasks (customer_phone);
CREATE INDEX customer_tasks_status_type_idx    ON customer_tasks (status, type);

CREATE TRIGGER set_updated_at_customer_tasks
  BEFORE UPDATE ON customer_tasks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
